### ISSUE TITLE
what's pvt_v2_ap in code?

### ISSUE THREAD

**Issue by lucasjinreal** [zhiqi-li/Panoptic-SegFormer#1]
I found there are many names that obscure to understand. For example: pvt_v2_ap what that stands for?
and what's single_stage_w_mask stands for?

![image](https://user-images.githubusercontent.com/21303438/144705454-7f27cba8-e600-4dd5-abd0-27c2a8504e9a.png)

and those file differences?

**Comment by zhiqi-li** [comment]
I am sorry that the codes make you confused. Due to the rush, the repo also contains a lot of useless codes (other versions used during the experiment). I will clean up these codes as soon as possible to avoid misunderstandings.

**Comment by zhiqi-li** [comment]
“pvt_v2_ap” refers to the [PVTv2](https://github.com/whai362/PVT) backbone with **a**verage **p**ooling
“ single_stage_w_mask” is modified from mmdet's "single_stage" and make it can handle masks
